version: '3'

services:

  postgres:
    image: 'bitnami/postgresql'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=database
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - app-net   


  redis:
    image: 'bitnami/redis'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    networks:
      - app-net 


